apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of pod
    x: helloashu 
  name: ashupod1 # name of pod 
spec:
  containers:
  - image: nginx
    name: ashupod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
