apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJkb2NrZXJhc2h1IiwicGFzc3dvcmQiOiJYeXpAMDk4IiwiYXV0aCI6IlpHOWphMlZ5WVhOb2RUcFllWHBBTURrNCJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ashu-cred
type: kubernetes.io/dockerconfigjson
